{% set name = "openlibm" %}
{% set version = "0.6.0" %}
{% set sha256 = "d45439093d1fd15e2ac3acf69955e462401c7a160d3330256cb4a86c51bdae28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JuliaLang/openlibm/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - {{ compiler("c") }}
  host:

test:
  commands:
    - test -d "${PREFIX}/include/openlibm"                            # [unix]
    - test -f "${PREFIX}/lib/libopenlibm.a"                           # [unix]
    - test -f "${PREFIX}/lib/libopenlibm${SHLIB_EXT}"                 # [unix]

about:
  home: http://openlibm.org/
  license: MIT, ISC, BSD 2-Clause
  license_file: LICENSE.md
  summary: "High quality system independent, portable, open source libm implementation"
  dev_url: https://github.com/JuliaLang/openlibm

extra:
  recipe-maintainers:
    - dfornika
    - jakirkham
