{% set name = "openlibm" %}
{% set version = "0.7.4" %}
{% set sha256 = "eb585204d6c995691e5545ea4ffcb887c159bf05cc5ee1bbf92a6fcdde2fccae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JuliaLang/openlibm/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler("c") }}  # [not win]
    - {{ compiler("m2w64_c") }}  # [win]
  host:

test:
  requires:
    - {{ compiler("c") }}
  files:
    - test_openlibm.c
  commands:
    - test -d "${PREFIX}/include/openlibm"                         # [unix]
    - test -f "${PREFIX}/lib/libopenlibm.a"                        # [unix]
    - test -f "${PREFIX}/lib/libopenlibm${SHLIB_EXT}"              # [unix]
    - if not exist "%LIBRARY_BIN%\\libopenlibm.dll" exit 1         # [win]
    - if not exist "%LIBRARY_INC%\\openlibm\\openlibm.h" exit 1    # [win]
    - if not exist "%LIBRARY_LIB%\\libopenlibm.lib" exit 1         # [win]
    - if not exist "%LIBRARY_LIB%\\libopenlibm_static.lib" exit 1  # [win]
    - echo on  # [win]
    - cl /Tc test_openlibm.c /I %CONDA_PREFIX%\Library\include\openlibm /link /LIBPATH:"%CONDA_PREFIX%\Library\lib" libopenlibm_static.lib /out:test_openlibm.exe  # [win]
    - test_openlibm.exe  # [win]
    - ${CC} -o test_openlibm test_openlibm.c -I${CONDA_PREFIX}/include/openlibm -L${CONDA_PREFIX}/lib -lopenlibm ${CFLAGS} ${LDFLAGS}  # [unix]
    - ./test_openlibm  # [unix]

about:
  home: http://openlibm.org/
  license: MIT, ISC, BSD 2-Clause
  license_file: LICENSE.md
  summary: "High quality system independent, portable, open source libm implementation"
  dev_url: https://github.com/JuliaLang/openlibm

extra:
  recipe-maintainers:
    - dfornika
    - jakirkham
    - SylvainCorlay
