{% set name = "openlibm" %}
{% set version = "0.5.5" %}
{% set sha256 = "07dcc5f59e695fb45167c81406b8e201c5ad91ebf24e3e55ae13298670910cfd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JuliaLang/openlibm/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler("c") }}
  host:

test:
  commands:
    - test -d "${PREFIX}/include/openlibm"                            # [unix]
    - test -f "${PREFIX}/lib/libopenlibm.a"                           # [unix]
    - test -f "${PREFIX}/lib/libopenlibm${SHLIB_EXT}"                 # [unix]

about:
  home: http://openlibm.org/
  license: MIT, ISC, BSD 2-Clause
  license_file: LICENSE.md
  summary: "High quality system independent, portable, open source libm implementation"
  dev_url: https://github.com/JuliaLang/openlibm

extra:
  recipe-maintainers:
    - dfornika
    - jakirkham
