appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RRpVf7C7hYshkLeFrvcTBsBsfin2ReytuXQweUD5gKt5QyhdEkJdvsr4UMOlXTW67fSj50N0bY0SwXFmLSUDdQCVEoEscLUpfu7HUuUvC4pksLkbVoiDz0BRxOyrLkX579qdlLbkPs6C0hg8r1PvDN81U5HKXPLAvfzItz6Pwc8XdgH514/Ni5ShhHk8mD2SWI8xTz9m8zhwlmmMedc1VxA6rkLbmpfnAtXJ1mF/I0TUSNEPdjqkiVtpB66TqWS7sVo8wEaI0TUs8evSt4RDpKB9bMlrSJ0AIJZJxQhDQv0mbEeSw1CIztpRMRrsgRVZBiuGSf9s6bMPXawjjmVxD8tWcspKvUqkJ8WCmSTRgfnDl4+i55Soiu3U3LQs7hdpRi6bS5JDUpRH455QakFTs8DxKw82hEAtp5JNKq73a6rYtKZy/jrHwIM7snD6zWDLPTX7uSuo6bnIYTFE35Zi+q2a8zjDiG4aYvQ7RW6D2jNvA49RWrEfG32KdWGpDx4lb3V6gTWbtDbxISYWQCsP/3lz8gziw5zL6kZFqyQHiYtOkzHc1Dmy4nZRVBqMq8EAUfE1zn2tNL6kzmF/qZ7WgYW8Ce6OZUVr3LLwJhDxqKp/nXP7akcExZFWLrcYnuWOeM9ZzDHtOLNBIviWYYyKYgqRp7egHEi1FBdFly94wdQ=}
provider:
  win: azure
